default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: guarderia

test:
  <<: *default
  database: guarderia_test

production:
  <<: *default
  database: guarderia